name: Testing code
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.1'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B clean test
        
      - name: Telegram Notification
        if: ${{ always() }}
        uses: appleboy/telegram-action@master
        with: 
          to: $ {{ secrets.TELEGRAM_CHAT_ID }}
          token: $ {{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            $ {{ job.status }}: Tests ${{ job.status == 'success' && 'passed' || 'failed' }}.
